insert into funcao (fl_funcao, nm_funcao) values('S', 'Software Developer I');
insert into funcao (fl_funcao, nm_funcao) values('S', 'Software Developer II');
insert into funcao (fl_funcao, nm_funcao) values('S', 'Software Developer III');
insert into funcao (fl_funcao, nm_funcao) values('S', 'Business Analyst I');
insert into funcao (fl_funcao, nm_funcao) values('S', 'Business Analyst II');
insert into funcao (fl_funcao, nm_funcao) values('S', 'Business Analyst III');
insert into funcao (fl_funcao, nm_funcao) values('S', 'DevOps I');
insert into funcao (fl_funcao, nm_funcao) values('S', 'DevOps II');
insert into funcao (fl_funcao, nm_funcao) values('S', 'DevOps III');
insert into funcao (fl_funcao, nm_funcao) values('S', 'Gerente');